# Generated by Django 4.1.7 on 2023-05-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
