# Generated by Django 4.1.7 on 2023-05-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
